/**
 * 사자성어 100 — 지식타자 코스(sajaseongeo)와 타자 격투 필살기가 함께 쓰는 원본 데이터.
 * 게임 번들에 journey-data 전체가 딸려가지 않도록 별도 모듈로 둔다.
 */
import type { JourneyStation } from './journey-data';

export const SAJASEONGEO_GROUPS: { id: string; label: string }[] = [
  { id: 'effort', label: '노력·인내' },
  { id: 'friend', label: '우정·관계' },
  { id: 'wisdom', label: '지혜·처세' },
  { id: 'study', label: '학문·배움' },
  { id: 'family', label: '효·은혜' },
  { id: 'crisis', label: '위기·곤경' },
  { id: 'folly', label: '어리석음·경계' },
  { id: 'success', label: '성공·뛰어남' },
  { id: 'speech', label: '말·언행' },
  { id: 'world', label: '세상·비유' },
];

/** name=사자성어, reading=한자, fact=뜻(타이핑 대상), detail=풀이·유래(표시만) */
export const SAJASEONGEO: JourneyStation[] = [
  { id: 'i001', name: '고진감래', reading: '苦盡甘來', fact: '쓴 것이 다하면 단 것이 온다', detail: '고생 끝에 즐거움이 온다는 말로, 힘든 시기를 버티는 사람에게 건네는 격려입니다.', group: 'effort' },
  { id: 'i002', name: '우공이산', reading: '愚公移山', fact: '우직하게 한 우물을 파면 산도 옮긴다', detail: '우공이라는 노인이 대대로 흙을 날라 산을 옮기려 한 이야기에서 나왔습니다.', group: 'effort' },
  { id: 'i003', name: '마부작침', reading: '磨斧作針', fact: '도끼를 갈아 바늘을 만든다', detail: '이백이 도끼를 갈던 노파를 보고 학업을 다시 시작했다는 이야기에서 나왔습니다.', group: 'effort' },
  { id: 'i004', name: '와신상담', reading: '臥薪嘗膽', fact: '섶에 눕고 쓸개를 맛보며 복수를 다짐한다', detail: '오나라 부차와 월나라 구천이 원수를 갚으려 고통을 참은 고사에서 나왔습니다.', group: 'effort' },
  { id: 'i005', name: '형설지공', reading: '螢雪之功', fact: '반딧불과 눈빛으로 공부해 이룬 공', detail: '가난해 등불을 못 켜던 선비들이 반딧불과 눈빛에 책을 읽은 이야기에서 나왔습니다.', group: 'effort' },
  { id: 'i006', name: '절차탁마', reading: '切磋琢磨', fact: '옥돌을 자르고 갈고 쪼고 다듬는다', detail: '학문과 인격을 끊임없이 갈고닦는다는 뜻으로 시경에 나옵니다.', group: 'effort' },
  { id: 'i007', name: '대기만성', reading: '大器晩成', fact: '큰 그릇은 늦게 이루어진다', detail: '크게 될 사람은 오랜 노력 끝에 늦게 성공한다는 말입니다.', group: 'effort' },
  { id: 'i008', name: '칠전팔기', reading: '七顚八起', fact: '일곱 번 넘어져도 여덟 번 일어난다', detail: '여러 번 실패해도 굴하지 않고 다시 일어서는 태도를 말합니다.', group: 'effort' },
  { id: 'i009', name: '수적천석', reading: '水滴穿石', fact: '떨어지는 물방울이 돌을 뚫는다', detail: '작은 힘이라도 꾸준히 쌓이면 큰일을 이룬다는 말입니다.', group: 'effort' },
  { id: 'i010', name: '백절불굴', reading: '百折不屈', fact: '백 번 꺾여도 굽히지 않는다', detail: '어떤 어려움에도 뜻을 굽히지 않는 굳센 의지를 말합니다.', group: 'effort' },
  { id: 'i011', name: '관포지교', reading: '管鮑之交', fact: '관중과 포숙아의 변함없는 우정', detail: '포숙아가 끝까지 관중을 믿고 이해해 준 춘추시대 고사에서 나왔습니다.', group: 'friend' },
  { id: 'i012', name: '죽마고우', reading: '竹馬故友', fact: '대나무 말을 타고 놀던 옛 친구', detail: '어릴 때부터 함께 자란 오랜 친구를 이르는 말입니다.', group: 'friend' },
  { id: 'i013', name: '막역지우', reading: '莫逆之友', fact: '서로 거스름이 없는 친구', detail: '허물없이 마음이 통하는 아주 가까운 친구를 말합니다.', group: 'friend' },
  { id: 'i014', name: '수어지교', reading: '水魚之交', fact: '물과 물고기처럼 떨어질 수 없는 사이', detail: '유비가 제갈량과의 관계를 물고기와 물에 빗댄 데서 나왔습니다.', group: 'friend' },
  { id: 'i015', name: '금란지교', reading: '金蘭之交', fact: '쇠처럼 단단하고 난초처럼 향기로운 사귐', detail: '친구 사이의 두터운 우정을 이르는 말로 주역에서 나왔습니다.', group: 'friend' },
  { id: 'i016', name: '동병상련', reading: '同病相憐', fact: '같은 병을 앓는 사람끼리 서로 가엾게 여긴다', detail: '어려운 처지의 사람끼리 서로 이해하고 돕는 마음을 말합니다.', group: 'friend' },
  { id: 'i017', name: '역지사지', reading: '易地思之', fact: '처지를 바꾸어 생각한다', detail: '상대의 입장이 되어 헤아려 보라는 말로 맹자에서 나왔습니다.', group: 'friend' },
  { id: 'i018', name: '이심전심', reading: '以心傳心', fact: '마음에서 마음으로 전한다', detail: '말하지 않아도 서로 뜻이 통한다는 말로 불교에서 나왔습니다.', group: 'friend' },
  { id: 'i019', name: '순망치한', reading: '脣亡齒寒', fact: '입술이 없으면 이가 시리다', detail: '서로 기대는 사이에서 하나가 망하면 다른 하나도 위태롭다는 말입니다.', group: 'friend' },
  { id: 'i020', name: '백아절현', reading: '伯牙絶絃', fact: '백아가 거문고 줄을 끊었다', detail: '자기 음악을 알아주던 친구 종자기가 죽자 백아가 줄을 끊은 고사에서 나왔습니다.', group: 'friend' },
  { id: 'i021', name: '온고지신', reading: '溫故知新', fact: '옛것을 익혀 새것을 안다', detail: '지난 것을 충분히 익혀야 새로운 이치를 깨닫는다는 논어의 말입니다.', group: 'wisdom' },
  { id: 'i022', name: '과유불급', reading: '過猶不及', fact: '지나침은 모자람과 같다', detail: '무엇이든 알맞은 정도가 가장 좋다는 논어의 가르침입니다.', group: 'wisdom' },
  { id: 'i023', name: '유비무환', reading: '有備無患', fact: '준비가 있으면 근심이 없다', detail: '미리 대비해 두면 걱정할 일이 없다는 말로 서경에 나옵니다.', group: 'wisdom' },
  { id: 'i024', name: '새옹지마', reading: '塞翁之馬', fact: '변방 노인의 말', detail: '인생의 좋고 나쁜 일은 미리 알 수 없다는 뜻으로 회남자에 나옵니다.', group: 'wisdom' },
  { id: 'i025', name: '전화위복', reading: '轉禍爲福', fact: '재앙이 바뀌어 복이 된다', detail: '나쁜 일도 노력하면 오히려 좋은 결과로 바꿀 수 있다는 말입니다.', group: 'wisdom' },
  { id: 'i026', name: '타산지석', reading: '他山之石', fact: '다른 산의 돌도 옥을 가는 데 쓴다', detail: '남의 하찮은 언행도 나를 닦는 데 도움이 된다는 말입니다.', group: 'wisdom' },
  { id: 'i027', name: '반면교사', reading: '反面敎師', fact: '나쁜 본보기에서 배운다', detail: '남의 잘못을 보고 나는 그러지 말아야겠다고 깨닫는 것을 말합니다.', group: 'wisdom' },
  { id: 'i028', name: '사필귀정', reading: '事必歸正', fact: '모든 일은 반드시 바른 길로 돌아간다', detail: '처음에는 그릇되어도 결국 옳은 이치대로 된다는 말입니다.', group: 'wisdom' },
  { id: 'i029', name: '인과응보', reading: '因果應報', fact: '원인에 따라 결과를 받는다', detail: '좋은 일에는 좋은 결과가 나쁜 일에는 나쁜 결과가 따른다는 불교의 말입니다.', group: 'wisdom' },
  { id: 'i030', name: '자업자득', reading: '自業自得', fact: '자기가 한 일의 결과를 자기가 받는다', detail: '스스로 저지른 일의 대가를 스스로 치른다는 말입니다.', group: 'wisdom' },
  { id: 'i031', name: '교학상장', reading: '敎學相長', fact: '가르치고 배우며 서로 성장한다', detail: '가르치는 사람과 배우는 사람이 함께 발전한다는 예기의 말입니다.', group: 'study' },
  { id: 'i032', name: '불치하문', reading: '不恥下問', fact: '아랫사람에게 묻기를 부끄러워하지 않는다', detail: '모르는 것은 누구에게든 물어 배우는 겸손한 자세를 말합니다.', group: 'study' },
  { id: 'i033', name: '청출어람', reading: '靑出於藍', fact: '쪽에서 나온 푸른색이 쪽보다 더 푸르다', detail: '제자가 스승보다 더 뛰어나게 된 것을 이르는 말입니다.', group: 'study' },
  { id: 'i034', name: '괄목상대', reading: '刮目相對', fact: '눈을 비비고 다시 본다', detail: '남의 실력이 몰라볼 만큼 부쩍 늘었음을 이르는 말입니다.', group: 'study' },
  { id: 'i035', name: '일취월장', reading: '日就月將', fact: '날로 달로 자라고 나아간다', detail: '실력이 하루가 다르게 빠르게 발전함을 이르는 말입니다.', group: 'study' },
  { id: 'i036', name: '박학다식', reading: '博學多識', fact: '배운 것이 넓고 아는 것이 많다', detail: '여러 분야에 걸쳐 두루 많이 아는 사람을 이르는 말입니다.', group: 'study' },
  { id: 'i037', name: '주경야독', reading: '晝耕夜讀', fact: '낮에는 밭을 갈고 밤에는 글을 읽는다', detail: '바쁜 가운데서도 틈틈이 공부하는 부지런함을 말합니다.', group: 'study' },
  { id: 'i038', name: '독서삼매', reading: '讀書三昧', fact: '책 읽기에 푹 빠진 경지', detail: '다른 생각 없이 오직 책 읽기에만 몰두한 상태를 말합니다.', group: 'study' },
  { id: 'i039', name: '위편삼절', reading: '韋編三絶', fact: '책을 묶은 가죽 끈이 세 번 끊어졌다', detail: '공자가 주역을 수없이 읽어 끈이 닳아 끊어진 데서 나왔습니다.', group: 'study' },
  { id: 'i040', name: '맹모삼천', reading: '孟母三遷', fact: '맹자의 어머니가 세 번 이사했다', detail: '자식 교육을 위해 환경을 가려 세 번 이사한 이야기에서 나왔습니다.', group: 'study' },
  { id: 'i041', name: '반포지효', reading: '反哺之孝', fact: '까마귀가 늙은 어미에게 먹이를 물어다 주는 효', detail: '자식이 자라서 부모의 은혜를 갚는 효도를 말합니다.', group: 'family' },
  { id: 'i042', name: '혼정신성', reading: '昏定晨省', fact: '저녁에는 잠자리를 보고 아침에는 안부를 묻는다', detail: '부모를 정성껏 모시는 자식의 도리를 말합니다.', group: 'family' },
  { id: 'i043', name: '풍수지탄', reading: '風樹之歎', fact: '바람과 나무의 탄식', detail: '효도하려 할 때 이미 부모님이 계시지 않음을 슬퍼하는 말입니다.', group: 'family' },
  { id: 'i044', name: '망운지정', reading: '望雲之情', fact: '구름을 바라보며 어버이를 그리는 마음', detail: '객지에서 고향의 부모를 그리워하는 자식의 정을 말합니다.', group: 'family' },
  { id: 'i045', name: '반의지희', reading: '斑衣之戲', fact: '색동옷을 입고 재롱을 부린다', detail: '늙어서도 부모를 기쁘게 해드리려는 효심을 말합니다.', group: 'family' },
  { id: 'i046', name: '형우제공', reading: '兄友弟恭', fact: '형은 아우를 사랑하고 아우는 형을 공경한다', detail: '형제 사이의 우애를 이르는 말입니다.', group: 'family' },
  { id: 'i047', name: '부전자전', reading: '父傳子傳', fact: '아버지가 아들에게 대대로 전한다', detail: '아들이 아버지의 성격이나 습관을 그대로 닮았다는 말입니다.', group: 'family' },
  { id: 'i048', name: '결초보은', reading: '結草報恩', fact: '풀을 묶어 은혜를 갚는다', detail: '죽어서도 은혜를 잊지 않고 갚는다는 뜻으로 춘추좌씨전에 나옵니다.', group: 'family' },
  { id: 'i049', name: '각골난망', reading: '刻骨難忘', fact: '뼈에 새겨 잊기 어렵다', detail: '입은 은혜를 뼛속 깊이 새겨 잊지 않는다는 말입니다.', group: 'family' },
  { id: 'i050', name: '백골난망', reading: '白骨難忘', fact: '죽어 백골이 되어도 잊을 수 없다', detail: '남에게 큰 은혜를 입었을 때 고마움을 나타내는 말입니다.', group: 'family' },
  { id: 'i051', name: '사면초가', reading: '四面楚歌', fact: '사방에서 들리는 초나라 노래', detail: '항우가 사방이 적에게 둘러싸여 고립된 고사에서 나왔습니다.', group: 'crisis' },
  { id: 'i052', name: '진퇴양난', reading: '進退兩難', fact: '나아가기도 물러서기도 어렵다', detail: '이러지도 저러지도 못하는 곤란한 처지를 말합니다.', group: 'crisis' },
  { id: 'i053', name: '풍전등화', reading: '風前燈火', fact: '바람 앞의 등불', detail: '언제 꺼질지 모를 만큼 매우 위태로운 상황을 말합니다.', group: 'crisis' },
  { id: 'i054', name: '누란지위', reading: '累卵之危', fact: '알을 쌓아 놓은 것처럼 위태롭다', detail: '조금만 건드려도 무너질 듯한 아슬아슬한 형세를 말합니다.', group: 'crisis' },
  { id: 'i055', name: '백척간두', reading: '百尺竿頭', fact: '백 척 높이 장대 끝에 서 있다', detail: '더 나아갈 데 없는 매우 위태로운 지경을 말합니다.', group: 'crisis' },
  { id: 'i056', name: '설상가상', reading: '雪上加霜', fact: '눈 위에 서리가 더한다', detail: '어려운 일이 겹쳐서 일어남을 이르는 말입니다.', group: 'crisis' },
  { id: 'i057', name: '고립무원', reading: '孤立無援', fact: '홀로 떨어져 도움받을 데가 없다', detail: '고립되어 아무에게도 도움을 받을 수 없는 처지를 말합니다.', group: 'crisis' },
  { id: 'i058', name: '속수무책', reading: '束手無策', fact: '손이 묶여 방법이 없다', detail: '어찌할 도리가 없어 꼼짝 못 하는 상황을 말합니다.', group: 'crisis' },
  { id: 'i059', name: '오리무중', reading: '五里霧中', fact: '오 리에 걸친 안개 속', detail: '무슨 일인지 갈피를 잡을 수 없는 상태를 말합니다.', group: 'crisis' },
  { id: 'i060', name: '첩첩산중', reading: '疊疊山中', fact: '산이 겹겹이 둘러싼 깊은 산속', detail: '갈수록 어려운 일이 겹쳐 쌓여 있는 상황에도 씁니다.', group: 'crisis' },
  { id: 'i061', name: '수주대토', reading: '守株待兔', fact: '그루터기를 지키며 토끼를 기다린다', detail: '우연히 얻은 행운만 바라며 노력하지 않는 어리석음을 말합니다.', group: 'folly' },
  { id: 'i062', name: '각주구검', reading: '刻舟求劍', fact: '배에 표시를 새겨 칼을 찾는다', detail: '상황이 바뀐 줄 모르고 낡은 방식만 고집하는 어리석음을 말합니다.', group: 'folly' },
  { id: 'i063', name: '정저지와', reading: '井底之蛙', fact: '우물 안 개구리', detail: '넓은 세상을 모르고 좁은 소견에 갇힌 사람을 말합니다.', group: 'folly' },
  { id: 'i064', name: '연목구어', reading: '緣木求魚', fact: '나무에 올라가 물고기를 구한다', detail: '방법이 잘못되어 목적을 이룰 수 없음을 이르는 맹자의 말입니다.', group: 'folly' },
  { id: 'i065', name: '조삼모사', reading: '朝三暮四', fact: '아침에 세 개 저녁에 네 개', detail: '눈앞의 차이만 알고 결과가 같음을 모르는 어리석음을 말합니다.', group: 'folly' },
  { id: 'i066', name: '교각살우', reading: '矯角殺牛', fact: '뿔을 바로잡으려다 소를 죽인다', detail: '작은 흠을 고치려다 오히려 일을 크게 그르침을 말합니다.', group: 'folly' },
  { id: 'i067', name: '소탐대실', reading: '小貪大失', fact: '작은 것을 탐하다 큰 것을 잃는다', detail: '눈앞의 작은 이익에 매달리다 큰 손해를 본다는 말입니다.', group: 'folly' },
  { id: 'i068', name: '우이독경', reading: '牛耳讀經', fact: '소 귀에 경 읽기', detail: '아무리 가르쳐도 알아듣지 못함을 이르는 말입니다.', group: 'folly' },
  { id: 'i069', name: '사상누각', reading: '沙上樓閣', fact: '모래 위에 지은 누각', detail: '기초가 튼튼하지 않아 오래 버티지 못하는 것을 말합니다.', group: 'folly' },
  { id: 'i070', name: '자가당착', reading: '自家撞着', fact: '자기 말과 행동이 서로 어긋난다', detail: '앞뒤가 맞지 않아 스스로 모순에 빠짐을 말합니다.', group: 'folly' },
  { id: 'i071', name: '군계일학', reading: '群鷄一鶴', fact: '닭 무리 속의 한 마리 학', detail: '많은 사람 가운데 유난히 뛰어난 한 사람을 말합니다.', group: 'success' },
  { id: 'i072', name: '금상첨화', reading: '錦上添花', fact: '비단 위에 꽃을 더한다', detail: '좋은 일에 좋은 일이 더해짐을 이르는 말입니다.', group: 'success' },
  { id: 'i073', name: '일석이조', reading: '一石二鳥', fact: '돌 하나로 새 두 마리를 잡는다', detail: '한 가지 일로 두 가지 이득을 본다는 말입니다.', group: 'success' },
  { id: 'i074', name: '일거양득', reading: '一擧兩得', fact: '한 번 들어 둘을 얻는다', detail: '한 가지 일로 두 가지 이익을 얻음을 이르는 말입니다.', group: 'success' },
  { id: 'i075', name: '화룡점정', reading: '畵龍點睛', fact: '용을 그리고 마지막에 눈동자를 찍는다', detail: '일의 가장 중요한 부분을 마무리해 완성함을 말합니다.', group: 'success' },
  { id: 'i076', name: '입신양명', reading: '立身揚名', fact: '몸을 세우고 이름을 떨친다', detail: '출세하여 세상에 이름을 널리 알림을 말합니다.', group: 'success' },
  { id: 'i077', name: '금의환향', reading: '錦衣還鄕', fact: '비단옷을 입고 고향에 돌아온다', detail: '성공하여 고향에 돌아옴을 이르는 말입니다.', group: 'success' },
  { id: 'i078', name: '파죽지세', reading: '破竹之勢', fact: '대나무를 쪼개는 기세', detail: '거침없이 무섭게 밀고 나아가는 기세를 말합니다.', group: 'success' },
  { id: 'i079', name: '승승장구', reading: '乘勝長驅', fact: '이긴 기세를 타고 멀리 몰아친다', detail: '계속 이기며 거침없이 나아감을 이르는 말입니다.', group: 'success' },
  { id: 'i080', name: '백발백중', reading: '百發百中', fact: '백 번 쏘아 백 번 맞힌다', detail: '하는 일마다 예상이 딱 들어맞음을 이르는 말입니다.', group: 'success' },
  { id: 'i081', name: '언중유골', reading: '言中有骨', fact: '말 속에 뼈가 있다', detail: '예사로운 말 같지만 속에 단단한 뜻이 담겨 있음을 말합니다.', group: 'speech' },
  { id: 'i082', name: '감언이설', reading: '甘言利說', fact: '달콤한 말과 이로운 조건을 내세운 말', detail: '남을 꾀기 위해 듣기 좋게 꾸며낸 말을 이릅니다.', group: 'speech' },
  { id: 'i083', name: '교언영색', reading: '巧言令色', fact: '교묘한 말과 꾸민 얼굴빛', detail: '아첨하는 말과 태도를 경계하는 논어의 말입니다.', group: 'speech' },
  { id: 'i084', name: '유언비어', reading: '流言蜚語', fact: '근거 없이 떠도는 소문', detail: '아무 근거 없이 널리 퍼진 말을 이릅니다.', group: 'speech' },
  { id: 'i085', name: '일구이언', reading: '一口二言', fact: '한 입으로 두 말을 한다', detail: '말을 이랬다저랬다 바꾸는 것을 이르는 말입니다.', group: 'speech' },
  { id: 'i086', name: '촌철살인', reading: '寸鐵殺人', fact: '한 치의 쇠붙이로 사람을 죽인다', detail: '짧은 말 한마디로 핵심을 찌르는 것을 말합니다.', group: 'speech' },
  { id: 'i087', name: '청산유수', reading: '靑山流水', fact: '푸른 산에 흐르는 맑은 물', detail: '막힘없이 말을 잘하는 모습을 비유한 말입니다.', group: 'speech' },
  { id: 'i088', name: '동문서답', reading: '東問西答', fact: '동쪽을 묻는데 서쪽을 답한다', detail: '묻는 말과는 전혀 상관없는 엉뚱한 대답을 말합니다.', group: 'speech' },
  { id: 'i089', name: '어불성설', reading: '語不成說', fact: '말이 말이 되지 않는다', detail: '말이 도무지 이치에 맞지 않음을 이르는 말입니다.', group: 'speech' },
  { id: 'i090', name: '중언부언', reading: '重言復言', fact: '한 말을 자꾸 되풀이한다', detail: '이미 한 말을 쓸데없이 반복함을 이르는 말입니다.', group: 'speech' },
  { id: 'i091', name: '주객전도', reading: '主客顚倒', fact: '주인과 손님이 뒤바뀐다', detail: '중요한 것과 사소한 것의 순서가 뒤바뀜을 말합니다.', group: 'world' },
  { id: 'i092', name: '적반하장', reading: '賊反荷杖', fact: '도둑이 도리어 매를 든다', detail: '잘못한 사람이 오히려 큰소리치는 것을 말합니다.', group: 'world' },
  { id: 'i093', name: '호가호위', reading: '狐假虎威', fact: '여우가 호랑이의 위세를 빌린다', detail: '남의 힘을 빌려 위세를 부리는 것을 이르는 말입니다.', group: 'world' },
  { id: 'i094', name: '견물생심', reading: '見物生心', fact: '물건을 보면 욕심이 생긴다', detail: '실제로 보면 가지고 싶은 마음이 생긴다는 말입니다.', group: 'world' },
  { id: 'i095', name: '동상이몽', reading: '同床異夢', fact: '같은 자리에 누워 다른 꿈을 꾼다', detail: '함께 있으면서도 서로 다른 생각을 품고 있음을 말합니다.', group: 'world' },
  { id: 'i096', name: '오비이락', reading: '烏飛梨落', fact: '까마귀 날자 배 떨어진다', detail: '아무 관계 없는 일이 공교롭게 겹쳐 의심받는 것을 말합니다.', group: 'world' },
  { id: 'i097', name: '상전벽해', reading: '桑田碧海', fact: '뽕나무 밭이 푸른 바다가 된다', detail: '세상이 몰라볼 만큼 크게 바뀌었음을 이르는 말입니다.', group: 'world' },
  { id: 'i098', name: '격세지감', reading: '隔世之感', fact: '세대를 건너뛴 듯한 느낌', detail: '짧은 사이에 많이 변해 딴 세상 같은 느낌을 말합니다.', group: 'world' },
  { id: 'i099', name: '다다익선', reading: '多多益善', fact: '많으면 많을수록 더 좋다', detail: '한나라 한신이 자신은 병사가 많을수록 좋다고 한 데서 나왔습니다.', group: 'world' },
  { id: 'i100', name: '용두사미', reading: '龍頭蛇尾', fact: '용의 머리에 뱀의 꼬리', detail: '처음은 거창하지만 끝이 보잘것없음을 이르는 말입니다.', group: 'world' },
];
